// ─── Ad Bank ───────────────────────────────────────────────────────────────────
// 305 unique ad objects across 12 sectors for the VideoEV AdCP scoring engine.

export type QrType = "discount" | "appointment" | "info" | "test_drive";

export interface Ad {
  id: string;
  brand: string;
  sector: string;
  baseCpm: number;
  attributes: [string, string, string];
  qrType: QrType;
  videoUrl: string;
}

const S3 = "https://videoev.s3.us-east-1.amazonaws.com";

export const AD_BANK: Ad[] = [
  // ── Financial (25) ─────────────────────────────────────────────────────────
  { id: "f1a2b3c4-0001", brand: "Chase",             sector: "Financial",    baseCpm: 32.00, attributes: ["high_msrp", "commuter", "affluent"],        qrType: "info",      videoUrl: `${S3}/placeholder_chase.mp4` },
  { id: "f1a2b3c4-0002", brand: "American Express",  sector: "Financial",    baseCpm: 48.00, attributes: ["high_msrp", "traveler", "luxury_buyer"],    qrType: "info",      videoUrl: `${S3}/placeholder_amex.mp4` },
  { id: "f1a2b3c4-0003", brand: "Goldman Sachs",     sector: "Financial",    baseCpm: 55.00, attributes: ["high_msrp", "affluent", "investor"],        qrType: "appointment", videoUrl: `${S3}/placeholder_goldman.mp4` },
  { id: "f1a2b3c4-0004", brand: "Morgan Stanley",    sector: "Financial",    baseCpm: 52.00, attributes: ["high_msrp", "investor", "tech_professional"], qrType: "appointment", videoUrl: `${S3}/placeholder_morganstanley.mp4` },
  { id: "f1a2b3c4-0005", brand: "Fidelity",          sector: "Financial",    baseCpm: 35.00, attributes: ["investor", "family", "commuter"],           qrType: "info",      videoUrl: `${S3}/placeholder_fidelity.mp4` },
  { id: "f1a2b3c4-0006", brand: "Charles Schwab",    sector: "Financial",    baseCpm: 33.00, attributes: ["investor", "commuter", "affluent"],         qrType: "info",      videoUrl: `${S3}/placeholder_schwab.mp4` },
  { id: "f1a2b3c4-0007", brand: "Vanguard",          sector: "Financial",    baseCpm: 30.00, attributes: ["investor", "long_term", "family"],          qrType: "info",      videoUrl: `${S3}/placeholder_vanguard.mp4` },
  { id: "f1a2b3c4-0008", brand: "Citi",              sector: "Financial",    baseCpm: 28.00, attributes: ["traveler", "commuter", "urban"],             qrType: "discount",  videoUrl: `${S3}/placeholder_citi.mp4` },
  { id: "f1a2b3c4-0009", brand: "Wells Fargo",       sector: "Financial",    baseCpm: 25.00, attributes: ["family", "homeowner", "suburban"],          qrType: "info",      videoUrl: `${S3}/placeholder_wellsfargo.mp4` },
  { id: "f1a2b3c4-0010", brand: "Bank of America",   sector: "Financial",    baseCpm: 27.00, attributes: ["family", "commuter", "homeowner"],          qrType: "info",      videoUrl: `${S3}/placeholder_bofa.mp4` },
  { id: "f1a2b3c4-0011", brand: "Robinhood",         sector: "Financial",    baseCpm: 22.00, attributes: ["young_professional", "investor", "tech_enthusiast"], qrType: "discount", videoUrl: `${S3}/placeholder_robinhood.mp4` },
  { id: "f1a2b3c4-0012", brand: "SoFi",              sector: "Financial",    baseCpm: 26.00, attributes: ["young_professional", "refinance", "commuter"], qrType: "discount", videoUrl: `${S3}/placeholder_sofi.mp4` },
  { id: "f1a2b3c4-0013", brand: "Ally Bank",         sector: "Financial",    baseCpm: 24.00, attributes: ["online_native", "saver", "family"],         qrType: "discount",  videoUrl: `${S3}/placeholder_ally.mp4` },
  { id: "f1a2b3c4-0014", brand: "Betterment",        sector: "Financial",    baseCpm: 27.00, attributes: ["investor", "automated", "millennial"],      qrType: "info",      videoUrl: `${S3}/placeholder_betterment.mp4` },
  { id: "f1a2b3c4-0015", brand: "Wealthfront",       sector: "Financial",    baseCpm: 26.00, attributes: ["investor", "tech_professional", "automated"], qrType: "info",    videoUrl: `${S3}/placeholder_wealthfront.mp4` },
  { id: "f1a2b3c4-0016", brand: "Coinbase",          sector: "Financial",    baseCpm: 32.00, attributes: ["tech_enthusiast", "investor", "young_professional"], qrType: "discount", videoUrl: `${S3}/placeholder_coinbase.mp4` },
  { id: "f1a2b3c4-0017", brand: "PayPal",            sector: "Financial",    baseCpm: 20.00, attributes: ["online_native", "shopper", "commuter"],     qrType: "discount",  videoUrl: `${S3}/placeholder_paypal.mp4` },
  { id: "f1a2b3c4-0018", brand: "Venmo",             sector: "Financial",    baseCpm: 16.00, attributes: ["millennial", "social", "urban"],            qrType: "discount",  videoUrl: `${S3}/placeholder_venmo.mp4` },
  { id: "f1a2b3c4-0019", brand: "Cash App",          sector: "Financial",    baseCpm: 18.00, attributes: ["young_professional", "urban", "social"],    qrType: "discount",  videoUrl: `${S3}/placeholder_cashapp.mp4` },
  { id: "f1a2b3c4-0020", brand: "Mastercard",        sector: "Financial",    baseCpm: 42.00, attributes: ["high_msrp", "traveler", "affluent"],        qrType: "info",      videoUrl: `${S3}/placeholder_mastercard.mp4` },
  { id: "f1a2b3c4-0021", brand: "Discover",          sector: "Financial",    baseCpm: 24.00, attributes: ["family", "cashback", "commuter"],           qrType: "discount",  videoUrl: `${S3}/placeholder_discover.mp4` },
  { id: "f1a2b3c4-0022", brand: "E*TRADE",           sector: "Financial",    baseCpm: 29.00, attributes: ["investor", "trader", "affluent"],           qrType: "info",      videoUrl: `${S3}/placeholder_etrade.mp4` },
  { id: "f1a2b3c4-0023", brand: "Stripe",            sector: "Financial",    baseCpm: 38.00, attributes: ["tech_professional", "entrepreneur", "b2b"], qrType: "info",      videoUrl: `${S3}/placeholder_stripe.mp4` },
  { id: "f1a2b3c4-0024", brand: "USAA",              sector: "Financial",    baseCpm: 30.00, attributes: ["military", "family", "homeowner"],          qrType: "info",      videoUrl: `${S3}/placeholder_usaa.mp4` },
  { id: "f1a2b3c4-0025", brand: "Marcus by Goldman", sector: "Financial",    baseCpm: 28.00, attributes: ["saver", "affluent", "online_native"],       qrType: "discount",  videoUrl: `${S3}/placeholder_marcus.mp4` },

  // ── Luxury (25) ─────────────────────────────────────────────────────────────
  { id: "l2b3c4d5-0001", brand: "Tiffany & Co.",     sector: "Luxury",       baseCpm: 62.00, attributes: ["high_msrp", "luxury_buyer", "gifting"],     qrType: "info",      videoUrl: `${S3}/placeholder_tiffany.mp4` },
  { id: "l2b3c4d5-0002", brand: "Cartier",           sector: "Luxury",       baseCpm: 70.00, attributes: ["high_msrp", "luxury_buyer", "traveler"],    qrType: "appointment", videoUrl: `${S3}/placeholder_cartier.mp4` },
  { id: "l2b3c4d5-0003", brand: "Rolex",             sector: "Luxury",       baseCpm: 75.00, attributes: ["high_msrp", "affluent", "achiever"],        qrType: "info",      videoUrl: `${S3}/placeholder_rolex.mp4` },
  { id: "l2b3c4d5-0004", brand: "Louis Vuitton",     sector: "Luxury",       baseCpm: 80.00, attributes: ["high_msrp", "traveler", "luxury_buyer"],    qrType: "info",      videoUrl: `${S3}/placeholder_lv.mp4` },
  { id: "l2b3c4d5-0005", brand: "Gucci",             sector: "Luxury",       baseCpm: 72.00, attributes: ["high_msrp", "fashionista", "luxury_buyer"], qrType: "info",      videoUrl: `${S3}/placeholder_gucci.mp4` },
  { id: "l2b3c4d5-0006", brand: "Prada",             sector: "Luxury",       baseCpm: 68.00, attributes: ["high_msrp", "luxury_buyer", "fashionista"], qrType: "info",      videoUrl: `${S3}/placeholder_prada.mp4` },
  { id: "l2b3c4d5-0007", brand: "Hermès",            sector: "Luxury",       baseCpm: 85.00, attributes: ["high_msrp", "ultra_luxury", "gifting"],     qrType: "appointment", videoUrl: `${S3}/placeholder_hermes.mp4` },
  { id: "l2b3c4d5-0008", brand: "Chanel",            sector: "Luxury",       baseCpm: 78.00, attributes: ["high_msrp", "fashionista", "luxury_buyer"], qrType: "info",      videoUrl: `${S3}/placeholder_chanel.mp4` },
  { id: "l2b3c4d5-0009", brand: "Patek Philippe",    sector: "Luxury",       baseCpm: 90.00, attributes: ["high_msrp", "ultra_luxury", "collector"],   qrType: "appointment", videoUrl: `${S3}/placeholder_patek.mp4` },
  { id: "l2b3c4d5-0010", brand: "Dior",              sector: "Luxury",       baseCpm: 72.00, attributes: ["high_msrp", "fashionista", "luxury_buyer"], qrType: "info",      videoUrl: `${S3}/placeholder_dior.mp4` },
  { id: "l2b3c4d5-0011", brand: "Bulgari",           sector: "Luxury",       baseCpm: 66.00, attributes: ["high_msrp", "luxury_buyer", "traveler"],    qrType: "info",      videoUrl: `${S3}/placeholder_bulgari.mp4` },
  { id: "l2b3c4d5-0012", brand: "Breitling",         sector: "Luxury",       baseCpm: 65.00, attributes: ["high_msrp", "aviator", "achiever"],         qrType: "appointment", videoUrl: `${S3}/placeholder_breitling.mp4` },
  { id: "l2b3c4d5-0013", brand: "TAG Heuer",         sector: "Luxury",       baseCpm: 58.00, attributes: ["high_msrp", "sporty", "achiever"],          qrType: "appointment", videoUrl: `${S3}/placeholder_tagheuer.mp4` },
  { id: "l2b3c4d5-0014", brand: "Versace",           sector: "Luxury",       baseCpm: 64.00, attributes: ["high_msrp", "fashionista", "urban"],        qrType: "info",      videoUrl: `${S3}/placeholder_versace.mp4` },
  { id: "l2b3c4d5-0015", brand: "Bottega Veneta",    sector: "Luxury",       baseCpm: 70.00, attributes: ["high_msrp", "understated_luxury", "affluent"], qrType: "info",  videoUrl: `${S3}/placeholder_bottega.mp4` },
  { id: "l2b3c4d5-0016", brand: "Balenciaga",        sector: "Luxury",       baseCpm: 66.00, attributes: ["high_msrp", "streetwear", "fashionista"],   qrType: "info",      videoUrl: `${S3}/placeholder_balenciaga.mp4` },
  { id: "l2b3c4d5-0017", brand: "Saint Laurent",     sector: "Luxury",       baseCpm: 68.00, attributes: ["high_msrp", "fashionista", "luxury_buyer"], qrType: "info",      videoUrl: `${S3}/placeholder_ysl.mp4` },
  { id: "l2b3c4d5-0018", brand: "Burberry",          sector: "Luxury",       baseCpm: 60.00, attributes: ["high_msrp", "traveler", "british_heritage"], qrType: "info",     videoUrl: `${S3}/placeholder_burberry.mp4` },
  { id: "l2b3c4d5-0019", brand: "Audemars Piguet",   sector: "Luxury",       baseCpm: 88.00, attributes: ["high_msrp", "ultra_luxury", "collector"],   qrType: "appointment", videoUrl: `${S3}/placeholder_ap.mp4` },
  { id: "l2b3c4d5-0020", brand: "Chopard",           sector: "Luxury",       baseCpm: 72.00, attributes: ["high_msrp", "gifting", "luxury_buyer"],     qrType: "appointment", videoUrl: `${S3}/placeholder_chopard.mp4` },
  { id: "l2b3c4d5-0021", brand: "Maserati",          sector: "Luxury",       baseCpm: 55.00, attributes: ["high_msrp", "performance", "luxury_buyer"], qrType: "test_drive", videoUrl: `${S3}/placeholder_maserati.mp4` },
  { id: "l2b3c4d5-0022", brand: "Aston Martin",      sector: "Luxury",       baseCpm: 55.00, attributes: ["high_msrp", "performance", "ultra_luxury"], qrType: "test_drive", videoUrl: `${S3}/placeholder_astonmartin.mp4` },
  { id: "l2b3c4d5-0023", brand: "Bentley",           sector: "Luxury",       baseCpm: 55.00, attributes: ["high_msrp", "ultra_luxury", "comfort"],     qrType: "test_drive", videoUrl: `${S3}/placeholder_bentley.mp4` },
  { id: "l2b3c4d5-0024", brand: "IWC Schaffhausen",  sector: "Luxury",       baseCpm: 70.00, attributes: ["high_msrp", "aviator", "collector"],        qrType: "appointment", videoUrl: `${S3}/placeholder_iwc.mp4` },
  { id: "l2b3c4d5-0025", brand: "Rolls-Royce",       sector: "Luxury",       baseCpm: 55.00, attributes: ["high_msrp", "ultra_luxury", "chauffeur"],   qrType: "test_drive", videoUrl: `${S3}/placeholder_rollsroyce.mp4` },

  // ── Pharma / Health (25) ────────────────────────────────────────────────────
  { id: "p3c4d5e6-0001", brand: "CVS Health",        sector: "Pharma",       baseCpm: 20.00, attributes: ["family", "health_conscious", "suburban"],  qrType: "discount",  videoUrl: `${S3}/placeholder_cvs.mp4` },
  { id: "p3c4d5e6-0002", brand: "Walgreens",         sector: "Pharma",       baseCpm: 18.00, attributes: ["family", "commuter", "health_conscious"],  qrType: "discount",  videoUrl: `${S3}/placeholder_walgreens.mp4` },
  { id: "p3c4d5e6-0003", brand: "GoodRx",            sector: "Pharma",       baseCpm: 22.00, attributes: ["cost_conscious", "family", "commuter"],     qrType: "discount",  videoUrl: `${S3}/placeholder_goodrx.mp4` },
  { id: "p3c4d5e6-0004", brand: "Hims & Hers",       sector: "Pharma",       baseCpm: 28.00, attributes: ["millennial", "health_conscious", "urban"],  qrType: "info",      videoUrl: `${S3}/placeholder_hims.mp4` },
  { id: "p3c4d5e6-0005", brand: "Teladoc",           sector: "Pharma",       baseCpm: 22.00, attributes: ["family", "convenience", "suburban"],       qrType: "appointment", videoUrl: `${S3}/placeholder_teladoc.mp4` },
  { id: "p3c4d5e6-0006", brand: "One Medical",       sector: "Pharma",       baseCpm: 30.00, attributes: ["affluent", "health_conscious", "urban"],    qrType: "appointment", videoUrl: `${S3}/placeholder_onemedical.mp4` },
  { id: "p3c4d5e6-0007", brand: "Noom",              sector: "Pharma",       baseCpm: 20.00, attributes: ["health_conscious", "millennial", "family"], qrType: "discount",  videoUrl: `${S3}/placeholder_noom.mp4` },
  { id: "p3c4d5e6-0008", brand: "Novo Nordisk",      sector: "Pharma",       baseCpm: 38.00, attributes: ["health_conscious", "affluent", "family"],   qrType: "info",      videoUrl: `${S3}/placeholder_novonordisk.mp4` },
  { id: "p3c4d5e6-0009", brand: "Abbott",            sector: "Pharma",       baseCpm: 30.00, attributes: ["health_conscious", "family", "achiever"],   qrType: "info",      videoUrl: `${S3}/placeholder_abbott.mp4` },
  { id: "p3c4d5e6-0010", brand: "Pfizer",            sector: "Pharma",       baseCpm: 35.00, attributes: ["family", "health_conscious", "suburban"],   qrType: "info",      videoUrl: `${S3}/placeholder_pfizer.mp4` },
  { id: "p3c4d5e6-0011", brand: "Advil",             sector: "Pharma",       baseCpm: 16.00, attributes: ["commuter", "active", "family"],             qrType: "discount",  videoUrl: `${S3}/placeholder_advil.mp4` },
  { id: "p3c4d5e6-0012", brand: "Tylenol",           sector: "Pharma",       baseCpm: 14.00, attributes: ["family", "parent", "suburban"],             qrType: "discount",  videoUrl: `${S3}/placeholder_tylenol.mp4` },
  { id: "p3c4d5e6-0013", brand: "Claritin",          sector: "Pharma",       baseCpm: 15.00, attributes: ["outdoor_enthusiast", "family", "suburban"], qrType: "discount",  videoUrl: `${S3}/placeholder_claritin.mp4` },
  { id: "p3c4d5e6-0014", brand: "Zyrtec",            sector: "Pharma",       baseCpm: 16.00, attributes: ["outdoor_enthusiast", "commuter", "family"], qrType: "discount",  videoUrl: `${S3}/placeholder_zyrtec.mp4` },
  { id: "p3c4d5e6-0015", brand: "Allegra",           sector: "Pharma",       baseCpm: 14.00, attributes: ["outdoor_enthusiast", "suburban", "active"], qrType: "discount",  videoUrl: `${S3}/placeholder_allegra.mp4` },
  { id: "p3c4d5e6-0016", brand: "MDLive",            sector: "Pharma",       baseCpm: 20.00, attributes: ["convenience", "commuter", "suburban"],      qrType: "appointment", videoUrl: `${S3}/placeholder_mdlive.mp4` },
  { id: "p3c4d5e6-0017", brand: "HealthMarkets",     sector: "Pharma",       baseCpm: 20.00, attributes: ["family", "self_employed", "suburban"],      qrType: "info",      videoUrl: `${S3}/placeholder_healthmarkets.mp4` },
  { id: "p3c4d5e6-0018", brand: "Optum",             sector: "Pharma",       baseCpm: 32.00, attributes: ["corporate", "health_conscious", "family"],  qrType: "info",      videoUrl: `${S3}/placeholder_optum.mp4` },
  { id: "p3c4d5e6-0019", brand: "Ro (Roman)",        sector: "Pharma",       baseCpm: 25.00, attributes: ["millennial", "health_conscious", "male"],   qrType: "discount",  videoUrl: `${S3}/placeholder_roman.mp4` },
  { id: "p3c4d5e6-0020", brand: "MedExpress",        sector: "Pharma",       baseCpm: 18.00, attributes: ["commuter", "suburban", "family"],           qrType: "appointment", videoUrl: `${S3}/placeholder_medexpress.mp4` },
  { id: "p3c4d5e6-0021", brand: "Perrigo",           sector: "Pharma",       baseCpm: 14.00, attributes: ["cost_conscious", "family", "suburban"],     qrType: "discount",  videoUrl: `${S3}/placeholder_perrigo.mp4` },
  { id: "p3c4d5e6-0022", brand: "Merck",             sector: "Pharma",       baseCpm: 32.00, attributes: ["health_conscious", "affluent", "senior"],   qrType: "info",      videoUrl: `${S3}/placeholder_merck.mp4` },
  { id: "p3c4d5e6-0023", brand: "AstraZeneca",       sector: "Pharma",       baseCpm: 30.00, attributes: ["health_conscious", "family", "corporate"],  qrType: "info",      videoUrl: `${S3}/placeholder_astrazeneca.mp4` },
  { id: "p3c4d5e6-0024", brand: "Johnson & Johnson", sector: "Pharma",       baseCpm: 28.00, attributes: ["family", "parent", "health_conscious"],     qrType: "info",      videoUrl: `${S3}/placeholder_jnj.mp4` },
  { id: "p3c4d5e6-0025", brand: "Bayer",             sector: "Pharma",       baseCpm: 26.00, attributes: ["family", "active", "health_conscious"],     qrType: "discount",  videoUrl: `${S3}/placeholder_bayer.mp4` },

  // ── Legal (15) ──────────────────────────────────────────────────────────────
  { id: "g4d5e6f7-0001", brand: "LegalZoom",         sector: "Legal",        baseCpm: 22.00, attributes: ["entrepreneur", "small_business", "suburban"], qrType: "discount", videoUrl: `${S3}/placeholder_legalzoom.mp4` },
  { id: "g4d5e6f7-0002", brand: "Rocket Lawyer",     sector: "Legal",        baseCpm: 20.00, attributes: ["entrepreneur", "family", "homeowner"],       qrType: "discount",  videoUrl: `${S3}/placeholder_rocketlawyer.mp4` },
  { id: "g4d5e6f7-0003", brand: "JustAnswer",        sector: "Legal",        baseCpm: 18.00, attributes: ["family", "homeowner", "suburban"],           qrType: "info",      videoUrl: `${S3}/placeholder_justanswer.mp4` },
  { id: "g4d5e6f7-0004", brand: "Morgan & Morgan",   sector: "Legal",        baseCpm: 28.00, attributes: ["accident_prone", "family", "commuter"],      qrType: "info",      videoUrl: `${S3}/placeholder_morganmorgan.mp4` },
  { id: "g4d5e6f7-0005", brand: "LegalShield",       sector: "Legal",        baseCpm: 18.00, attributes: ["family", "small_business", "commuter"],      qrType: "discount",  videoUrl: `${S3}/placeholder_legalshield.mp4` },
  { id: "g4d5e6f7-0006", brand: "FindLaw",           sector: "Legal",        baseCpm: 15.00, attributes: ["family", "homeowner", "commuter"],           qrType: "info",      videoUrl: `${S3}/placeholder_findlaw.mp4` },
  { id: "g4d5e6f7-0007", brand: "Avvo",              sector: "Legal",        baseCpm: 14.00, attributes: ["urban", "renter", "commuter"],               qrType: "info",      videoUrl: `${S3}/placeholder_avvo.mp4` },
  { id: "g4d5e6f7-0008", brand: "LawDepot",          sector: "Legal",        baseCpm: 16.00, attributes: ["entrepreneur", "small_business", "homeowner"], qrType: "discount", videoUrl: `${S3}/placeholder_lawdepot.mp4` },
  { id: "g4d5e6f7-0009", brand: "Martindale",        sector: "Legal",        baseCpm: 18.00, attributes: ["affluent", "homeowner", "suburban"],         qrType: "appointment", videoUrl: `${S3}/placeholder_martindale.mp4` },
  { id: "g4d5e6f7-0010", brand: "Jacoby & Meyers",   sector: "Legal",        baseCpm: 20.00, attributes: ["commuter", "accident_prone", "family"],      qrType: "info",      videoUrl: `${S3}/placeholder_jacoby.mp4` },
  { id: "g4d5e6f7-0011", brand: "Nolo",              sector: "Legal",        baseCpm: 14.00, attributes: ["entrepreneur", "self_employed", "homeowner"], qrType: "info",     videoUrl: `${S3}/placeholder_nolo.mp4` },
  { id: "g4d5e6f7-0012", brand: "US Legal Services", sector: "Legal",        baseCpm: 16.00, attributes: ["family", "employee", "suburban"],            qrType: "discount",  videoUrl: `${S3}/placeholder_usls.mp4` },
  { id: "g4d5e6f7-0013", brand: "Class Action Connect", sector: "Legal",     baseCpm: 20.00, attributes: ["consumer", "family", "commuter"],            qrType: "info",      videoUrl: `${S3}/placeholder_classaction.mp4` },
  { id: "g4d5e6f7-0014", brand: "Injury Help Hotline", sector: "Legal",      baseCpm: 22.00, attributes: ["commuter", "accident_prone", "family"],      qrType: "info",      videoUrl: `${S3}/placeholder_injuryhelp.mp4` },
  { id: "g4d5e6f7-0015", brand: "Rocket Legal+",     sector: "Legal",        baseCpm: 22.00, attributes: ["small_business", "entrepreneur", "homeowner"], qrType: "discount", videoUrl: `${S3}/placeholder_rocketlegalplus.mp4` },

  // ── Home Services (25) ──────────────────────────────────────────────────────
  { id: "h5e6f7g8-0001", brand: "Angi",              sector: "Home Services", baseCpm: 18.00, attributes: ["homeowner", "suburban", "family"],          qrType: "discount",  videoUrl: `${S3}/placeholder_angi.mp4` },
  { id: "h5e6f7g8-0002", brand: "TaskRabbit",        sector: "Home Services", baseCpm: 16.00, attributes: ["urban", "renter", "millennial"],            qrType: "discount",  videoUrl: `${S3}/placeholder_taskrabbit.mp4` },
  { id: "h5e6f7g8-0003", brand: "Handy",             sector: "Home Services", baseCpm: 15.00, attributes: ["renter", "urban", "convenience"],           qrType: "discount",  videoUrl: `${S3}/placeholder_handy.mp4` },
  { id: "h5e6f7g8-0004", brand: "Thumbtack",         sector: "Home Services", baseCpm: 16.00, attributes: ["homeowner", "suburban", "diy_helper"],      qrType: "discount",  videoUrl: `${S3}/placeholder_thumbtack.mp4` },
  { id: "h5e6f7g8-0005", brand: "ADT",               sector: "Home Services", baseCpm: 22.00, attributes: ["homeowner", "family", "suburban"],          qrType: "discount",  videoUrl: `${S3}/placeholder_adt.mp4` },
  { id: "h5e6f7g8-0006", brand: "Vivint",            sector: "Home Services", baseCpm: 26.00, attributes: ["homeowner", "tech_enthusiast", "family"],   qrType: "discount",  videoUrl: `${S3}/placeholder_vivint.mp4` },
  { id: "h5e6f7g8-0007", brand: "Sunrun",            sector: "Home Services", baseCpm: 28.00, attributes: ["homeowner", "eco_conscious", "suburban"],   qrType: "appointment", videoUrl: `${S3}/placeholder_sunrun.mp4` },
  { id: "h5e6f7g8-0008", brand: "Terminix",          sector: "Home Services", baseCpm: 18.00, attributes: ["homeowner", "suburban", "family"],          qrType: "discount",  videoUrl: `${S3}/placeholder_terminix.mp4` },
  { id: "h5e6f7g8-0009", brand: "Orkin",             sector: "Home Services", baseCpm: 16.00, attributes: ["homeowner", "suburban", "family"],          qrType: "discount",  videoUrl: `${S3}/placeholder_orkin.mp4` },
  { id: "h5e6f7g8-0010", brand: "Stanley Steemer",   sector: "Home Services", baseCpm: 14.00, attributes: ["homeowner", "family", "suburban"],          qrType: "discount",  videoUrl: `${S3}/placeholder_stanleysteemer.mp4` },
  { id: "h5e6f7g8-0011", brand: "Molly Maid",        sector: "Home Services", baseCpm: 15.00, attributes: ["homeowner", "busy_professional", "suburban"], qrType: "discount", videoUrl: `${S3}/placeholder_mollymaid.mp4` },
  { id: "h5e6f7g8-0012", brand: "Roto-Rooter",       sector: "Home Services", baseCpm: 16.00, attributes: ["homeowner", "suburban", "family"],          qrType: "info",      videoUrl: `${S3}/placeholder_rotorooter.mp4` },
  { id: "h5e6f7g8-0013", brand: "Mr. Appliance",     sector: "Home Services", baseCpm: 14.00, attributes: ["homeowner", "family", "suburban"],          qrType: "appointment", videoUrl: `${S3}/placeholder_mrappliance.mp4` },
  { id: "h5e6f7g8-0014", brand: "HelloTech",         sector: "Home Services", baseCpm: 18.00, attributes: ["tech_enthusiast", "homeowner", "suburban"], qrType: "appointment", videoUrl: `${S3}/placeholder_hellotech.mp4` },
  { id: "h5e6f7g8-0015", brand: "ServiceMaster",     sector: "Home Services", baseCpm: 16.00, attributes: ["homeowner", "suburban", "family"],          qrType: "discount",  videoUrl: `${S3}/placeholder_servicemaster.mp4` },
  { id: "h5e6f7g8-0016", brand: "TruGreen",          sector: "Home Services", baseCpm: 18.00, attributes: ["homeowner", "suburban", "curb_appeal"],     qrType: "discount",  videoUrl: `${S3}/placeholder_trugreen.mp4` },
  { id: "h5e6f7g8-0017", brand: "Porch",             sector: "Home Services", baseCpm: 14.00, attributes: ["homeowner", "diy_helper", "suburban"],      qrType: "discount",  videoUrl: `${S3}/placeholder_porch.mp4` },
  { id: "h5e6f7g8-0018", brand: "ServPro",           sector: "Home Services", baseCpm: 18.00, attributes: ["homeowner", "suburban", "family"],          qrType: "info",      videoUrl: `${S3}/placeholder_servpro.mp4` },
  { id: "h5e6f7g8-0019", brand: "Mr. Electric",      sector: "Home Services", baseCpm: 16.00, attributes: ["homeowner", "suburban", "family"],          qrType: "appointment", videoUrl: `${S3}/placeholder_mrelectric.mp4` },
  { id: "h5e6f7g8-0020", brand: "Aire Serv",         sector: "Home Services", baseCpm: 16.00, attributes: ["homeowner", "suburban", "climate_sensitive"], qrType: "appointment", videoUrl: `${S3}/placeholder_aireserv.mp4` },
  { id: "h5e6f7g8-0021", brand: "Sears Home Services", sector: "Home Services", baseCpm: 16.00, attributes: ["homeowner", "suburban", "family"],        qrType: "appointment", videoUrl: `${S3}/placeholder_searshome.mp4` },
  { id: "h5e6f7g8-0022", brand: "Two Men and a Truck", sector: "Home Services", baseCpm: 15.00, attributes: ["mover", "suburban", "family"],           qrType: "discount",  videoUrl: `${S3}/placeholder_twomen.mp4` },
  { id: "h5e6f7g8-0023", brand: "PODS",              sector: "Home Services", baseCpm: 20.00, attributes: ["mover", "homeowner", "suburban"],           qrType: "discount",  videoUrl: `${S3}/placeholder_pods.mp4` },
  { id: "h5e6f7g8-0024", brand: "1-800-GOT-JUNK",    sector: "Home Services", baseCpm: 14.00, attributes: ["homeowner", "downsizer", "suburban"],       qrType: "discount",  videoUrl: `${S3}/placeholder_1800gotjunk.mp4` },
  { id: "h5e6f7g8-0025", brand: "Carvana Home",      sector: "Home Services", baseCpm: 20.00, attributes: ["homeowner", "tech_enthusiast", "suburban"], qrType: "appointment", videoUrl: `${S3}/placeholder_carvanahome.mp4` },

  // ── Home Furniture (20) ─────────────────────────────────────────────────────
  { id: "i6f7g8h9-0001", brand: "IKEA",              sector: "Furniture",    baseCpm: 16.00, attributes: ["homeowner", "millennial", "value_seeker"],  qrType: "discount",  videoUrl: `${S3}/placeholder_ikea.mp4` },
  { id: "i6f7g8h9-0002", brand: "Pottery Barn",      sector: "Furniture",    baseCpm: 28.00, attributes: ["homeowner", "affluent", "nesting"],         qrType: "info",      videoUrl: `${S3}/placeholder_potterybarn.mp4` },
  { id: "i6f7g8h9-0003", brand: "West Elm",          sector: "Furniture",    baseCpm: 26.00, attributes: ["millennial", "homeowner", "design_conscious"], qrType: "discount", videoUrl: `${S3}/placeholder_westelm.mp4` },
  { id: "i6f7g8h9-0004", brand: "RH",                sector: "Furniture",    baseCpm: 55.00, attributes: ["high_msrp", "affluent", "nesting"],          qrType: "appointment", videoUrl: `${S3}/placeholder_rh.mp4` },
  { id: "i6f7g8h9-0005", brand: "Crate & Barrel",    sector: "Furniture",    baseCpm: 30.00, attributes: ["homeowner", "affluent", "design_conscious"], qrType: "info",      videoUrl: `${S3}/placeholder_cb.mp4` },
  { id: "i6f7g8h9-0006", brand: "Williams-Sonoma",   sector: "Furniture",    baseCpm: 32.00, attributes: ["homeowner", "affluent", "cook"],             qrType: "discount",  videoUrl: `${S3}/placeholder_williamssonoma.mp4` },
  { id: "i6f7g8h9-0007", brand: "Wayfair",           sector: "Furniture",    baseCpm: 22.00, attributes: ["homeowner", "value_seeker", "online_native"], qrType: "discount", videoUrl: `${S3}/placeholder_wayfair.mp4` },
  { id: "i6f7g8h9-0008", brand: "Ashley Furniture",  sector: "Furniture",    baseCpm: 18.00, attributes: ["homeowner", "family", "suburban"],          qrType: "discount",  videoUrl: `${S3}/placeholder_ashley.mp4` },
  { id: "i6f7g8h9-0009", brand: "La-Z-Boy",          sector: "Furniture",    baseCpm: 16.00, attributes: ["homeowner", "comfort_seeker", "suburban"],  qrType: "discount",  videoUrl: `${S3}/placeholder_lazboy.mp4` },
  { id: "i6f7g8h9-0010", brand: "Ethan Allen",       sector: "Furniture",    baseCpm: 28.00, attributes: ["homeowner", "affluent", "traditional"],     qrType: "appointment", videoUrl: `${S3}/placeholder_ethanallen.mp4` },
  { id: "i6f7g8h9-0011", brand: "Arhaus",            sector: "Furniture",    baseCpm: 32.00, attributes: ["homeowner", "design_conscious", "affluent"], qrType: "appointment", videoUrl: `${S3}/placeholder_arhaus.mp4` },
  { id: "i6f7g8h9-0012", brand: "CB2",               sector: "Furniture",    baseCpm: 24.00, attributes: ["urban", "millennial", "design_conscious"],  qrType: "discount",  videoUrl: `${S3}/placeholder_cb2.mp4` },
  { id: "i6f7g8h9-0013", brand: "Article",           sector: "Furniture",    baseCpm: 20.00, attributes: ["millennial", "homeowner", "design_conscious"], qrType: "discount", videoUrl: `${S3}/placeholder_article.mp4` },
  { id: "i6f7g8h9-0014", brand: "Joybird",           sector: "Furniture",    baseCpm: 18.00, attributes: ["millennial", "homeowner", "personalization"], qrType: "discount", videoUrl: `${S3}/placeholder_joybird.mp4` },
  { id: "i6f7g8h9-0015", brand: "Design Within Reach", sector: "Furniture",  baseCpm: 38.00, attributes: ["affluent", "design_conscious", "urban"],    qrType: "appointment", videoUrl: `${S3}/placeholder_dwr.mp4` },
  { id: "i6f7g8h9-0016", brand: "Serena & Lily",     sector: "Furniture",    baseCpm: 34.00, attributes: ["affluent", "nesting", "coastal"],           qrType: "info",      videoUrl: `${S3}/placeholder_serena.mp4` },
  { id: "i6f7g8h9-0017", brand: "Anthropologie Home", sector: "Furniture",   baseCpm: 30.00, attributes: ["fashionista", "homeowner", "design_conscious"], qrType: "info",   videoUrl: `${S3}/placeholder_anthro.mp4` },
  { id: "i6f7g8h9-0018", brand: "Z Gallerie",        sector: "Furniture",    baseCpm: 22.00, attributes: ["urban", "design_conscious", "millennial"],  qrType: "discount",  videoUrl: `${S3}/placeholder_zgallerie.mp4` },
  { id: "i6f7g8h9-0019", brand: "Benchmade Modern",  sector: "Furniture",    baseCpm: 26.00, attributes: ["homeowner", "design_conscious", "affluent"], qrType: "appointment", videoUrl: `${S3}/placeholder_benchmade.mp4` },
  { id: "i6f7g8h9-0020", brand: "Restoration Hardware", sector: "Furniture", baseCpm: 50.00, attributes: ["high_msrp", "affluent", "nesting"],         qrType: "appointment", videoUrl: `${S3}/placeholder_restoration.mp4` },

  // ── Travel (25) ─────────────────────────────────────────────────────────────
  { id: "t7g8h9i0-0001", brand: "Delta Air Lines",   sector: "Travel",       baseCpm: 42.00, attributes: ["traveler", "business_class", "high_msrp"],  qrType: "discount",  videoUrl: `${S3}/placeholder_delta.mp4` },
  { id: "t7g8h9i0-0002", brand: "United Airlines",   sector: "Travel",       baseCpm: 38.00, attributes: ["traveler", "commuter", "business_class"],   qrType: "discount",  videoUrl: `${S3}/placeholder_united.mp4` },
  { id: "t7g8h9i0-0003", brand: "American Airlines", sector: "Travel",       baseCpm: 36.00, attributes: ["traveler", "commuter", "family"],            qrType: "discount",  videoUrl: `${S3}/placeholder_aa.mp4` },
  { id: "t7g8h9i0-0004", brand: "JetBlue",           sector: "Travel",       baseCpm: 28.00, attributes: ["traveler", "millennial", "leisure"],         qrType: "discount",  videoUrl: `${S3}/placeholder_jetblue.mp4` },
  { id: "t7g8h9i0-0005", brand: "Emirates",          sector: "Travel",       baseCpm: 65.00, attributes: ["high_msrp", "traveler", "luxury_buyer"],     qrType: "info",      videoUrl: `${S3}/placeholder_emirates.mp4` },
  { id: "t7g8h9i0-0006", brand: "British Airways",   sector: "Travel",       baseCpm: 55.00, attributes: ["high_msrp", "traveler", "business_class"],   qrType: "info",      videoUrl: `${S3}/placeholder_ba.mp4` },
  { id: "t7g8h9i0-0007", brand: "Marriott Bonvoy",   sector: "Travel",       baseCpm: 45.00, attributes: ["traveler", "business_class", "affluent"],    qrType: "discount",  videoUrl: `${S3}/placeholder_marriott.mp4` },
  { id: "t7g8h9i0-0008", brand: "Hilton Honors",     sector: "Travel",       baseCpm: 42.00, attributes: ["traveler", "business_class", "commuter"],    qrType: "discount",  videoUrl: `${S3}/placeholder_hilton.mp4` },
  { id: "t7g8h9i0-0009", brand: "Hyatt",             sector: "Travel",       baseCpm: 50.00, attributes: ["traveler", "affluent", "luxury_buyer"],      qrType: "discount",  videoUrl: `${S3}/placeholder_hyatt.mp4` },
  { id: "t7g8h9i0-0010", brand: "Four Seasons",      sector: "Travel",       baseCpm: 80.00, attributes: ["high_msrp", "ultra_luxury", "traveler"],     qrType: "appointment", videoUrl: `${S3}/placeholder_fourseasons.mp4` },
  { id: "t7g8h9i0-0011", brand: "Ritz-Carlton",      sector: "Travel",       baseCpm: 85.00, attributes: ["high_msrp", "ultra_luxury", "traveler"],     qrType: "appointment", videoUrl: `${S3}/placeholder_ritzcarlton.mp4` },
  { id: "t7g8h9i0-0012", brand: "Airbnb",            sector: "Travel",       baseCpm: 32.00, attributes: ["traveler", "millennial", "leisure"],         qrType: "discount",  videoUrl: `${S3}/placeholder_airbnb.mp4` },
  { id: "t7g8h9i0-0013", brand: "Expedia",           sector: "Travel",       baseCpm: 30.00, attributes: ["traveler", "family", "value_seeker"],        qrType: "discount",  videoUrl: `${S3}/placeholder_expedia.mp4` },
  { id: "t7g8h9i0-0014", brand: "Booking.com",       sector: "Travel",       baseCpm: 28.00, attributes: ["traveler", "value_seeker", "online_native"], qrType: "discount",  videoUrl: `${S3}/placeholder_booking.mp4` },
  { id: "t7g8h9i0-0015", brand: "Norwegian Cruise",  sector: "Travel",       baseCpm: 52.00, attributes: ["traveler", "leisure", "affluent"],           qrType: "discount",  videoUrl: `${S3}/placeholder_ncl.mp4` },
  { id: "t7g8h9i0-0016", brand: "Royal Caribbean",   sector: "Travel",       baseCpm: 48.00, attributes: ["traveler", "family", "leisure"],             qrType: "discount",  videoUrl: `${S3}/placeholder_rci.mp4` },
  { id: "t7g8h9i0-0017", brand: "Celebrity Cruises", sector: "Travel",       baseCpm: 58.00, attributes: ["traveler", "affluent", "luxury_buyer"],      qrType: "appointment", videoUrl: `${S3}/placeholder_celebrity.mp4` },
  { id: "t7g8h9i0-0018", brand: "Alaska Airlines",   sector: "Travel",       baseCpm: 32.00, attributes: ["traveler", "commuter", "leisure"],           qrType: "discount",  videoUrl: `${S3}/placeholder_alaska.mp4` },
  { id: "t7g8h9i0-0019", brand: "Southwest",         sector: "Travel",       baseCpm: 26.00, attributes: ["value_seeker", "traveler", "family"],        qrType: "discount",  videoUrl: `${S3}/placeholder_southwest.mp4` },
  { id: "t7g8h9i0-0020", brand: "TripAdvisor",       sector: "Travel",       baseCpm: 20.00, attributes: ["traveler", "research_driven", "family"],     qrType: "info",      videoUrl: `${S3}/placeholder_tripadvisor.mp4` },
  { id: "t7g8h9i0-0021", brand: "Kayak",             sector: "Travel",       baseCpm: 22.00, attributes: ["traveler", "value_seeker", "tech_enthusiast"], qrType: "discount", videoUrl: `${S3}/placeholder_kayak.mp4` },
  { id: "t7g8h9i0-0022", brand: "Sandals Resorts",   sector: "Travel",       baseCpm: 55.00, attributes: ["traveler", "couple", "luxury_buyer"],        qrType: "appointment", videoUrl: `${S3}/placeholder_sandals.mp4` },
  { id: "t7g8h9i0-0023", brand: "Vrbo",              sector: "Travel",       baseCpm: 28.00, attributes: ["traveler", "family", "homeowner"],           qrType: "discount",  videoUrl: `${S3}/placeholder_vrbo.mp4` },
  { id: "t7g8h9i0-0024", brand: "Priceline",         sector: "Travel",       baseCpm: 20.00, attributes: ["value_seeker", "traveler", "spontaneous"],   qrType: "discount",  videoUrl: `${S3}/placeholder_priceline.mp4` },
  { id: "t7g8h9i0-0025", brand: "Hotels.com",        sector: "Travel",       baseCpm: 24.00, attributes: ["traveler", "value_seeker", "family"],        qrType: "discount",  videoUrl: `${S3}/placeholder_hotelscom.mp4` },

  // ── Insurance (20) ──────────────────────────────────────────────────────────
  { id: "n8h9i0j1-0001", brand: "State Farm",        sector: "Insurance",    baseCpm: 28.00, attributes: ["homeowner", "family", "suburban"],          qrType: "info",      videoUrl: `${S3}/placeholder_statefarm.mp4` },
  { id: "n8h9i0j1-0002", brand: "Allstate",          sector: "Insurance",    baseCpm: 26.00, attributes: ["homeowner", "family", "commuter"],          qrType: "info",      videoUrl: `${S3}/placeholder_allstate.mp4` },
  { id: "n8h9i0j1-0003", brand: "GEICO",             sector: "Insurance",    baseCpm: 22.00, attributes: ["commuter", "value_seeker", "family"],        qrType: "discount",  videoUrl: `${S3}/placeholder_geico.mp4` },
  { id: "n8h9i0j1-0004", brand: "Progressive",       sector: "Insurance",    baseCpm: 20.00, attributes: ["commuter", "value_seeker", "young_driver"],  qrType: "discount",  videoUrl: `${S3}/placeholder_progressive.mp4` },
  { id: "n8h9i0j1-0005", brand: "Farmers",           sector: "Insurance",    baseCpm: 24.00, attributes: ["homeowner", "family", "suburban"],          qrType: "info",      videoUrl: `${S3}/placeholder_farmers.mp4` },
  { id: "n8h9i0j1-0006", brand: "Liberty Mutual",    sector: "Insurance",    baseCpm: 22.00, attributes: ["family", "homeowner", "commuter"],          qrType: "discount",  videoUrl: `${S3}/placeholder_libertymutual.mp4` },
  { id: "n8h9i0j1-0007", brand: "Nationwide",        sector: "Insurance",    baseCpm: 22.00, attributes: ["homeowner", "family", "suburban"],          qrType: "info",      videoUrl: `${S3}/placeholder_nationwide.mp4` },
  { id: "n8h9i0j1-0008", brand: "Travelers",         sector: "Insurance",    baseCpm: 24.00, attributes: ["homeowner", "affluent", "family"],          qrType: "info",      videoUrl: `${S3}/placeholder_travelers.mp4` },
  { id: "n8h9i0j1-0009", brand: "Lemonade",          sector: "Insurance",    baseCpm: 26.00, attributes: ["renter", "urban", "millennial"],            qrType: "discount",  videoUrl: `${S3}/placeholder_lemonade.mp4` },
  { id: "n8h9i0j1-0010", brand: "Hippo Insurance",   sector: "Insurance",    baseCpm: 24.00, attributes: ["homeowner", "tech_enthusiast", "suburban"], qrType: "discount",  videoUrl: `${S3}/placeholder_hippo.mp4` },
  { id: "n8h9i0j1-0011", brand: "Amica",             sector: "Insurance",    baseCpm: 26.00, attributes: ["homeowner", "affluent", "family"],          qrType: "info",      videoUrl: `${S3}/placeholder_amica.mp4` },
  { id: "n8h9i0j1-0012", brand: "MetLife",           sector: "Insurance",    baseCpm: 24.00, attributes: ["family", "corporate", "homeowner"],         qrType: "info",      videoUrl: `${S3}/placeholder_metlife.mp4` },
  { id: "n8h9i0j1-0013", brand: "Prudential",        sector: "Insurance",    baseCpm: 28.00, attributes: ["affluent", "family", "long_term"],          qrType: "appointment", videoUrl: `${S3}/placeholder_prudential.mp4` },
  { id: "n8h9i0j1-0014", brand: "Chubb",             sector: "Insurance",    baseCpm: 35.00, attributes: ["high_msrp", "affluent", "homeowner"],       qrType: "appointment", videoUrl: `${S3}/placeholder_chubb.mp4` },
  { id: "n8h9i0j1-0015", brand: "USAA Insurance",    sector: "Insurance",    baseCpm: 30.00, attributes: ["military", "family", "homeowner"],          qrType: "info",      videoUrl: `${S3}/placeholder_usaainsurance.mp4` },
  { id: "n8h9i0j1-0016", brand: "AIG",               sector: "Insurance",    baseCpm: 30.00, attributes: ["affluent", "homeowner", "investor"],        qrType: "appointment", videoUrl: `${S3}/placeholder_aig.mp4` },
  { id: "n8h9i0j1-0017", brand: "Erie Insurance",    sector: "Insurance",    baseCpm: 22.00, attributes: ["homeowner", "family", "suburban"],          qrType: "info",      videoUrl: `${S3}/placeholder_erie.mp4` },
  { id: "n8h9i0j1-0018", brand: "Auto-Owners",       sector: "Insurance",    baseCpm: 22.00, attributes: ["homeowner", "family", "suburban"],          qrType: "info",      videoUrl: `${S3}/placeholder_autoowners.mp4` },
  { id: "n8h9i0j1-0019", brand: "The Hartford",      sector: "Insurance",    baseCpm: 26.00, attributes: ["small_business", "homeowner", "senior"],    qrType: "info",      videoUrl: `${S3}/placeholder_hartford.mp4` },
  { id: "n8h9i0j1-0020", brand: "Country Financial", sector: "Insurance",    baseCpm: 20.00, attributes: ["homeowner", "rural", "family"],             qrType: "info",      videoUrl: `${S3}/placeholder_countryfinancial.mp4` },

  // ── QSR (25) ────────────────────────────────────────────────────────────────
  { id: "q9i0j1k2-0001", brand: "McDonald's",        sector: "QSR",          baseCpm: 22.00, attributes: ["commuter", "family", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_mcdonalds.mp4` },
  { id: "q9i0j1k2-0002", brand: "Starbucks",         sector: "QSR",          baseCpm: 28.00, attributes: ["commuter", "professional", "morning"],      qrType: "discount",  videoUrl: `${S3}/placeholder_starbucks.mp4` },
  { id: "q9i0j1k2-0003", brand: "Chipotle",          sector: "QSR",          baseCpm: 24.00, attributes: ["millennial", "health_conscious", "commuter"], qrType: "discount", videoUrl: `${S3}/placeholder_chipotle.mp4` },
  { id: "q9i0j1k2-0004", brand: "Taco Bell",         sector: "QSR",          baseCpm: 18.00, attributes: ["millennial", "young_professional", "urban"], qrType: "discount",  videoUrl: `${S3}/placeholder_tacobell.mp4` },
  { id: "q9i0j1k2-0005", brand: "Chick-fil-A",       sector: "QSR",          baseCpm: 22.00, attributes: ["family", "suburban", "health_conscious"],   qrType: "discount",  videoUrl: `${S3}/placeholder_chickfila.mp4` },
  { id: "q9i0j1k2-0006", brand: "Shake Shack",       sector: "QSR",          baseCpm: 26.00, attributes: ["urban", "affluent", "foodie"],              qrType: "discount",  videoUrl: `${S3}/placeholder_shakeshack.mp4` },
  { id: "q9i0j1k2-0007", brand: "Dunkin'",           sector: "QSR",          baseCpm: 20.00, attributes: ["commuter", "morning", "value_seeker"],      qrType: "discount",  videoUrl: `${S3}/placeholder_dunkin.mp4` },
  { id: "q9i0j1k2-0008", brand: "Panera Bread",      sector: "QSR",          baseCpm: 20.00, attributes: ["professional", "health_conscious", "commuter"], qrType: "discount", videoUrl: `${S3}/placeholder_panera.mp4` },
  { id: "q9i0j1k2-0009", brand: "Wendy's",           sector: "QSR",          baseCpm: 16.00, attributes: ["commuter", "family", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_wendys.mp4` },
  { id: "q9i0j1k2-0010", brand: "Burger King",       sector: "QSR",          baseCpm: 18.00, attributes: ["commuter", "family", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_burgerking.mp4` },
  { id: "q9i0j1k2-0011", brand: "Subway",            sector: "QSR",          baseCpm: 16.00, attributes: ["commuter", "health_conscious", "value_seeker"], qrType: "discount", videoUrl: `${S3}/placeholder_subway.mp4` },
  { id: "q9i0j1k2-0012", brand: "Domino's",          sector: "QSR",          baseCpm: 18.00, attributes: ["family", "evening", "value_seeker"],        qrType: "discount",  videoUrl: `${S3}/placeholder_dominos.mp4` },
  { id: "q9i0j1k2-0013", brand: "Pizza Hut",         sector: "QSR",          baseCpm: 16.00, attributes: ["family", "suburban", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_pizzahut.mp4` },
  { id: "q9i0j1k2-0014", brand: "KFC",               sector: "QSR",          baseCpm: 16.00, attributes: ["commuter", "family", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_kfc.mp4` },
  { id: "q9i0j1k2-0015", brand: "Popeyes",           sector: "QSR",          baseCpm: 18.00, attributes: ["commuter", "family", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_popeyes.mp4` },
  { id: "q9i0j1k2-0016", brand: "Five Guys",         sector: "QSR",          baseCpm: 20.00, attributes: ["urban", "foodie", "young_professional"],    qrType: "discount",  videoUrl: `${S3}/placeholder_fiveguys.mp4` },
  { id: "q9i0j1k2-0017", brand: "Wingstop",          sector: "QSR",          baseCpm: 18.00, attributes: ["millennial", "urban", "sports_fan"],        qrType: "discount",  videoUrl: `${S3}/placeholder_wingstop.mp4` },
  { id: "q9i0j1k2-0018", brand: "Raising Cane's",    sector: "QSR",          baseCpm: 20.00, attributes: ["millennial", "commuter", "value_seeker"],   qrType: "discount",  videoUrl: `${S3}/placeholder_canes.mp4` },
  { id: "q9i0j1k2-0019", brand: "In-N-Out",          sector: "QSR",          baseCpm: 24.00, attributes: ["commuter", "value_seeker", "west_coast"],   qrType: "info",      videoUrl: `${S3}/placeholder_innout.mp4` },
  { id: "q9i0j1k2-0020", brand: "Dairy Queen",       sector: "QSR",          baseCpm: 14.00, attributes: ["family", "suburban", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_dq.mp4` },
  { id: "q9i0j1k2-0021", brand: "Sonic",             sector: "QSR",          baseCpm: 15.00, attributes: ["commuter", "suburban", "value_seeker"],     qrType: "discount",  videoUrl: `${S3}/placeholder_sonic.mp4` },
  { id: "q9i0j1k2-0022", brand: "Whataburger",       sector: "QSR",          baseCpm: 18.00, attributes: ["commuter", "south_texas", "value_seeker"],  qrType: "discount",  videoUrl: `${S3}/placeholder_whataburger.mp4` },
  { id: "q9i0j1k2-0023", brand: "Denny's",           sector: "QSR",          baseCpm: 12.00, attributes: ["commuter", "suburban", "family"],           qrType: "discount",  videoUrl: `${S3}/placeholder_dennys.mp4` },
  { id: "q9i0j1k2-0024", brand: "IHOP",              sector: "QSR",          baseCpm: 13.00, attributes: ["family", "suburban", "morning"],            qrType: "discount",  videoUrl: `${S3}/placeholder_ihop.mp4` },
  { id: "q9i0j1k2-0025", brand: "Olive Garden",      sector: "QSR",          baseCpm: 16.00, attributes: ["family", "suburban", "celebration"],        qrType: "discount",  videoUrl: `${S3}/placeholder_olivegarden.mp4` },

  // ── Automotive (25) ─────────────────────────────────────────────────────────
  { id: "a0j1k2l3-0001", brand: "Ford",              sector: "Automotive",   baseCpm: 34.00, attributes: ["truck_buyer", "american", "suburban"],      qrType: "test_drive", videoUrl: `${S3}/placeholder_ford.mp4` },
  { id: "a0j1k2l3-0002", brand: "Chevrolet",         sector: "Automotive",   baseCpm: 30.00, attributes: ["truck_buyer", "american", "suburban"],      qrType: "test_drive", videoUrl: `${S3}/placeholder_chevy.mp4` },
  { id: "a0j1k2l3-0003", brand: "Toyota",            sector: "Automotive",   baseCpm: 32.00, attributes: ["family", "commuter", "reliable"],           qrType: "test_drive", videoUrl: `${S3}/placeholder_toyota.mp4` },
  { id: "a0j1k2l3-0004", brand: "Honda",             sector: "Automotive",   baseCpm: 28.00, attributes: ["family", "commuter", "reliable"],           qrType: "test_drive", videoUrl: `${S3}/placeholder_honda.mp4` },
  { id: "a0j1k2l3-0005", brand: "Hyundai",           sector: "Automotive",   baseCpm: 26.00, attributes: ["value_seeker", "tech_enthusiast", "commuter"], qrType: "test_drive", videoUrl: `${S3}/placeholder_hyundai.mp4` },
  { id: "a0j1k2l3-0006", brand: "Kia",               sector: "Automotive",   baseCpm: 24.00, attributes: ["value_seeker", "young_professional", "commuter"], qrType: "test_drive", videoUrl: `${S3}/placeholder_kia.mp4` },
  { id: "a0j1k2l3-0007", brand: "Volkswagen",        sector: "Automotive",   baseCpm: 28.00, attributes: ["commuter", "european", "design_conscious"], qrType: "test_drive", videoUrl: `${S3}/placeholder_vw.mp4` },
  { id: "a0j1k2l3-0008", brand: "Subaru",            sector: "Automotive",   baseCpm: 26.00, attributes: ["outdoor_enthusiast", "family", "all_wheel_drive"], qrType: "test_drive", videoUrl: `${S3}/placeholder_subaru.mp4` },
  { id: "a0j1k2l3-0009", brand: "Lexus",             sector: "Automotive",   baseCpm: 52.00, attributes: ["high_msrp", "affluent", "commuter"],        qrType: "test_drive", videoUrl: `${S3}/placeholder_lexus.mp4` },
  { id: "a0j1k2l3-0010", brand: "Acura",             sector: "Automotive",   baseCpm: 42.00, attributes: ["high_msrp", "performance", "commuter"],     qrType: "test_drive", videoUrl: `${S3}/placeholder_acura.mp4` },
  { id: "a0j1k2l3-0011", brand: "Infiniti",          sector: "Automotive",   baseCpm: 44.00, attributes: ["high_msrp", "luxury_buyer", "commuter"],    qrType: "test_drive", videoUrl: `${S3}/placeholder_infiniti.mp4` },
  { id: "a0j1k2l3-0012", brand: "Lincoln",           sector: "Automotive",   baseCpm: 48.00, attributes: ["high_msrp", "affluent", "comfort_seeker"],  qrType: "test_drive", videoUrl: `${S3}/placeholder_lincoln.mp4` },
  { id: "a0j1k2l3-0013", brand: "Cadillac",          sector: "Automotive",   baseCpm: 50.00, attributes: ["high_msrp", "american_luxury", "affluent"], qrType: "test_drive", videoUrl: `${S3}/placeholder_cadillac.mp4` },
  { id: "a0j1k2l3-0014", brand: "Jeep",              sector: "Automotive",   baseCpm: 32.00, attributes: ["outdoor_enthusiast", "adventure", "family"], qrType: "test_drive", videoUrl: `${S3}/placeholder_jeep.mp4` },
  { id: "a0j1k2l3-0015", brand: "Ram Trucks",        sector: "Automotive",   baseCpm: 28.00, attributes: ["truck_buyer", "american", "suburban"],      qrType: "test_drive", videoUrl: `${S3}/placeholder_ram.mp4` },
  { id: "a0j1k2l3-0016", brand: "CarMax",            sector: "Automotive",   baseCpm: 22.00, attributes: ["car_buyer", "value_seeker", "commuter"],    qrType: "info",       videoUrl: `${S3}/placeholder_carmax.mp4` },
  { id: "a0j1k2l3-0017", brand: "Carvana",           sector: "Automotive",   baseCpm: 20.00, attributes: ["car_buyer", "tech_enthusiast", "online_native"], qrType: "info",  videoUrl: `${S3}/placeholder_carvana.mp4` },
  { id: "a0j1k2l3-0018", brand: "Goodyear",          sector: "Automotive",   baseCpm: 18.00, attributes: ["commuter", "family", "suburban"],           qrType: "discount",  videoUrl: `${S3}/placeholder_goodyear.mp4` },
  { id: "a0j1k2l3-0019", brand: "Bridgestone",       sector: "Automotive",   baseCpm: 20.00, attributes: ["commuter", "performance", "family"],        qrType: "discount",  videoUrl: `${S3}/placeholder_bridgestone.mp4` },
  { id: "a0j1k2l3-0020", brand: "Pep Boys",          sector: "Automotive",   baseCpm: 14.00, attributes: ["commuter", "diy", "suburban"],              qrType: "discount",  videoUrl: `${S3}/placeholder_pepboys.mp4` },
  { id: "a0j1k2l3-0021", brand: "AutoNation",        sector: "Automotive",   baseCpm: 20.00, attributes: ["car_buyer", "suburban", "family"],          qrType: "test_drive", videoUrl: `${S3}/placeholder_autonation.mp4` },
  { id: "a0j1k2l3-0022", brand: "Firestone",         sector: "Automotive",   baseCpm: 15.00, attributes: ["commuter", "family", "suburban"],           qrType: "discount",  videoUrl: `${S3}/placeholder_firestone.mp4` },
  { id: "a0j1k2l3-0023", brand: "Jiffy Lube",        sector: "Automotive",   baseCpm: 14.00, attributes: ["commuter", "convenience", "suburban"],      qrType: "discount",  videoUrl: `${S3}/placeholder_jiffylube.mp4` },
  { id: "a0j1k2l3-0024", brand: "CARFAX",            sector: "Automotive",   baseCpm: 18.00, attributes: ["car_buyer", "research_driven", "commuter"], qrType: "info",      videoUrl: `${S3}/placeholder_carfax.mp4` },
  { id: "a0j1k2l3-0025", brand: "TrueCar",           sector: "Automotive",   baseCpm: 20.00, attributes: ["car_buyer", "value_seeker", "online_native"], qrType: "info",    videoUrl: `${S3}/placeholder_truecar.mp4` },

  // ── Grocery (20) ────────────────────────────────────────────────────────────
  { id: "r1k2l3m4-0001", brand: "Whole Foods",       sector: "Grocery",      baseCpm: 22.00, attributes: ["health_conscious", "affluent", "urban"],    qrType: "discount",  videoUrl: `${S3}/placeholder_wholefoods.mp4` },
  { id: "r1k2l3m4-0002", brand: "Trader Joe's",      sector: "Grocery",      baseCpm: 20.00, attributes: ["health_conscious", "millennial", "urban"],  qrType: "discount",  videoUrl: `${S3}/placeholder_traderjoes.mp4` },
  { id: "r1k2l3m4-0003", brand: "Kroger",            sector: "Grocery",      baseCpm: 18.00, attributes: ["family", "value_seeker", "suburban"],       qrType: "discount",  videoUrl: `${S3}/placeholder_kroger.mp4` },
  { id: "r1k2l3m4-0004", brand: "Publix",            sector: "Grocery",      baseCpm: 20.00, attributes: ["family", "suburban", "southern"],           qrType: "discount",  videoUrl: `${S3}/placeholder_publix.mp4` },
  { id: "r1k2l3m4-0005", brand: "H-E-B",             sector: "Grocery",      baseCpm: 20.00, attributes: ["family", "suburban", "texas"],              qrType: "discount",  videoUrl: `${S3}/placeholder_heb.mp4` },
  { id: "r1k2l3m4-0006", brand: "Aldi",              sector: "Grocery",      baseCpm: 16.00, attributes: ["value_seeker", "family", "suburban"],       qrType: "discount",  videoUrl: `${S3}/placeholder_aldi.mp4` },
  { id: "r1k2l3m4-0007", brand: "Costco",            sector: "Grocery",      baseCpm: 22.00, attributes: ["family", "bulk_buyer", "suburban"],         qrType: "info",      videoUrl: `${S3}/placeholder_costco.mp4` },
  { id: "r1k2l3m4-0008", brand: "Sprouts",           sector: "Grocery",      baseCpm: 20.00, attributes: ["health_conscious", "suburban", "family"],   qrType: "discount",  videoUrl: `${S3}/placeholder_sprouts.mp4` },
  { id: "r1k2l3m4-0009", brand: "Thrive Market",     sector: "Grocery",      baseCpm: 22.00, attributes: ["health_conscious", "online_native", "eco_conscious"], qrType: "discount", videoUrl: `${S3}/placeholder_thrivemarket.mp4` },
  { id: "r1k2l3m4-0010", brand: "FreshDirect",       sector: "Grocery",      baseCpm: 20.00, attributes: ["urban", "convenience", "commuter"],         qrType: "discount",  videoUrl: `${S3}/placeholder_freshdirect.mp4` },
  { id: "r1k2l3m4-0011", brand: "Sam's Club",        sector: "Grocery",      baseCpm: 18.00, attributes: ["family", "bulk_buyer", "suburban"],         qrType: "discount",  videoUrl: `${S3}/placeholder_samsclub.mp4` },
  { id: "r1k2l3m4-0012", brand: "Meijer",            sector: "Grocery",      baseCpm: 16.00, attributes: ["family", "suburban", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_meijer.mp4` },
  { id: "r1k2l3m4-0013", brand: "Albertsons",        sector: "Grocery",      baseCpm: 16.00, attributes: ["family", "suburban", "commuter"],           qrType: "discount",  videoUrl: `${S3}/placeholder_albertsons.mp4` },
  { id: "r1k2l3m4-0014", brand: "Safeway",           sector: "Grocery",      baseCpm: 16.00, attributes: ["family", "suburban", "commuter"],           qrType: "discount",  videoUrl: `${S3}/placeholder_safeway.mp4` },
  { id: "r1k2l3m4-0015", brand: "Giant Food",        sector: "Grocery",      baseCpm: 15.00, attributes: ["family", "suburban", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_giant.mp4` },
  { id: "r1k2l3m4-0016", brand: "Food Lion",         sector: "Grocery",      baseCpm: 14.00, attributes: ["family", "suburban", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_foodlion.mp4` },
  { id: "r1k2l3m4-0017", brand: "Winn-Dixie",        sector: "Grocery",      baseCpm: 14.00, attributes: ["family", "southern", "value_seeker"],       qrType: "discount",  videoUrl: `${S3}/placeholder_winndixie.mp4` },
  { id: "r1k2l3m4-0018", brand: "Stop & Shop",       sector: "Grocery",      baseCpm: 15.00, attributes: ["family", "northeast", "commuter"],          qrType: "discount",  videoUrl: `${S3}/placeholder_stopandshop.mp4` },
  { id: "r1k2l3m4-0019", brand: "Harris Teeter",     sector: "Grocery",      baseCpm: 18.00, attributes: ["health_conscious", "suburban", "affluent"], qrType: "discount",  videoUrl: `${S3}/placeholder_harristeeter.mp4` },
  { id: "r1k2l3m4-0020", brand: "Natural Grocers",   sector: "Grocery",      baseCpm: 18.00, attributes: ["health_conscious", "eco_conscious", "suburban"], qrType: "discount", videoUrl: `${S3}/placeholder_naturalgrocers.mp4` },

  // ── Tech (25) ───────────────────────────────────────────────────────────────
  { id: "e2l3m4n5-0001", brand: "Apple",             sector: "Tech",         baseCpm: 52.00, attributes: ["high_msrp", "tech_enthusiast", "affluent"],  qrType: "info",      videoUrl: `${S3}/Apple+iPhone+17+Pro+TV+Spot+Smart+Group+Selfies+Song+by+Inspector+Spacetime+-+iSpot.mp4` },
  { id: "e2l3m4n5-0002", brand: "Samsung",           sector: "Tech",         baseCpm: 44.00, attributes: ["tech_enthusiast", "affluent", "commuter"],   qrType: "info",      videoUrl: `${S3}/placeholder_samsung.mp4` },
  { id: "e2l3m4n5-0003", brand: "Google",            sector: "Tech",         baseCpm: 48.00, attributes: ["tech_enthusiast", "commuter", "millennial"], qrType: "info",      videoUrl: `${S3}/placeholder_google.mp4` },
  { id: "e2l3m4n5-0004", brand: "Microsoft",         sector: "Tech",         baseCpm: 45.00, attributes: ["corporate", "tech_professional", "commuter"], qrType: "info",     videoUrl: `${S3}/placeholder_microsoft.mp4` },
  { id: "e2l3m4n5-0005", brand: "Amazon",            sector: "Tech",         baseCpm: 38.00, attributes: ["online_native", "shopper", "commuter"],      qrType: "discount",  videoUrl: `${S3}/Amazon+TV+Spot+Train+Robbery+-+iSpot.mp4` },
  { id: "e2l3m4n5-0006", brand: "Sony",              sector: "Tech",         baseCpm: 36.00, attributes: ["gamer", "audiophile", "tech_enthusiast"],    qrType: "info",      videoUrl: `${S3}/placeholder_sony.mp4` },
  { id: "e2l3m4n5-0007", brand: "LG",                sector: "Tech",         baseCpm: 30.00, attributes: ["homeowner", "tech_enthusiast", "family"],    qrType: "discount",  videoUrl: `${S3}/placeholder_lg.mp4` },
  { id: "e2l3m4n5-0008", brand: "Dell",              sector: "Tech",         baseCpm: 28.00, attributes: ["corporate", "tech_professional", "commuter"], qrType: "info",     videoUrl: `${S3}/placeholder_dell.mp4` },
  { id: "e2l3m4n5-0009", brand: "Best Buy",          sector: "Tech",         baseCpm: 26.00, attributes: ["tech_enthusiast", "shopper", "suburban"],    qrType: "discount",  videoUrl: `${S3}/placeholder_bestbuy.mp4` },
  { id: "e2l3m4n5-0010", brand: "Adobe",             sector: "Tech",         baseCpm: 40.00, attributes: ["creative", "tech_professional", "millennial"], qrType: "discount", videoUrl: `${S3}/placeholder_adobe.mp4` },
  { id: "e2l3m4n5-0011", brand: "Salesforce",        sector: "Tech",         baseCpm: 48.00, attributes: ["corporate", "b2b", "entrepreneur"],         qrType: "info",      videoUrl: `${S3}/placeholder_salesforce.mp4` },
  { id: "e2l3m4n5-0012", brand: "Zoom",              sector: "Tech",         baseCpm: 34.00, attributes: ["corporate", "remote_worker", "commuter"],    qrType: "discount",  videoUrl: `${S3}/placeholder_zoom.mp4` },
  { id: "e2l3m4n5-0013", brand: "Slack",             sector: "Tech",         baseCpm: 36.00, attributes: ["corporate", "tech_professional", "urban"],   qrType: "discount",  videoUrl: `${S3}/placeholder_slack.mp4` },
  { id: "e2l3m4n5-0014", brand: "Dropbox",           sector: "Tech",         baseCpm: 28.00, attributes: ["remote_worker", "tech_professional", "commuter"], qrType: "discount", videoUrl: `${S3}/placeholder_dropbox.mp4` },
  { id: "e2l3m4n5-0015", brand: "GitHub",            sector: "Tech",         baseCpm: 40.00, attributes: ["tech_professional", "developer", "urban"],   qrType: "info",      videoUrl: `${S3}/placeholder_github.mp4` },
  { id: "e2l3m4n5-0016", brand: "Canva",             sector: "Tech",         baseCpm: 28.00, attributes: ["creative", "small_business", "millennial"], qrType: "discount",  videoUrl: `${S3}/placeholder_canva.mp4` },
  { id: "e2l3m4n5-0017", brand: "Notion",            sector: "Tech",         baseCpm: 30.00, attributes: ["tech_professional", "remote_worker", "millennial"], qrType: "discount", videoUrl: `${S3}/placeholder_notion.mp4` },
  { id: "e2l3m4n5-0018", brand: "HubSpot",           sector: "Tech",         baseCpm: 36.00, attributes: ["entrepreneur", "small_business", "b2b"],    qrType: "info",      videoUrl: `${S3}/placeholder_hubspot.mp4` },
  { id: "e2l3m4n5-0019", brand: "Shopify",           sector: "Tech",         baseCpm: 38.00, attributes: ["entrepreneur", "small_business", "online_native"], qrType: "discount", videoUrl: `${S3}/placeholder_shopify.mp4` },
  { id: "e2l3m4n5-0020", brand: "Monday.com",        sector: "Tech",         baseCpm: 32.00, attributes: ["corporate", "b2b", "remote_worker"],        qrType: "discount",  videoUrl: `${S3}/placeholder_monday.mp4` },
  { id: "e2l3m4n5-0021", brand: "Figma",             sector: "Tech",         baseCpm: 34.00, attributes: ["creative", "tech_professional", "designer"], qrType: "discount",  videoUrl: `${S3}/placeholder_figma.mp4` },
  { id: "e2l3m4n5-0022", brand: "Stripe",            sector: "Tech",         baseCpm: 38.00, attributes: ["entrepreneur", "developer", "b2b"],         qrType: "info",      videoUrl: `${S3}/placeholder_stripe_tech.mp4` },
  { id: "e2l3m4n5-0023", brand: "Twilio",            sector: "Tech",         baseCpm: 36.00, attributes: ["developer", "b2b", "tech_professional"],    qrType: "info",      videoUrl: `${S3}/placeholder_twilio.mp4` },
  { id: "e2l3m4n5-0024", brand: "Cloudflare",        sector: "Tech",         baseCpm: 38.00, attributes: ["developer", "b2b", "tech_professional"],    qrType: "info",      videoUrl: `${S3}/placeholder_cloudflare.mp4` },
  { id: "e2l3m4n5-0025", brand: "Vercel",            sector: "Tech",         baseCpm: 32.00, attributes: ["developer", "tech_professional", "startup"], qrType: "info",      videoUrl: `${S3}/placeholder_vercel.mp4` },
];
